### ISSUE TITLE
Work with a more recent version of Hugo

### ISSUE THREAD

**Issue by davorg** [manwar/theweeklychallenge#110]
I installed the version of Hugo that's available from the Fedora package repos (`sudo dnf install hugo`). That gave me version [v0.93.3](https://github.com/gohugoio/hugo/releases/tag/v0.93.3) and when I ran `hugo` or `hugo serve`, I got a pile of errors (which I'll include in a comment). From the discussion on https://github.com/manwar/theweeklychallenge/issues/98, it looks like it works with [v0.67.0](https://github.com/gohugoio/hugo/releases/tag/v0.67.0), which is over three years old. Even the Fedora version I installed is a year old - the current version is (v0.114.1)[https://github.com/gohugoio/hugo/releases/tag/v0.114.1].

Asking people to install older versions of the software is going to be a barrier to getting people to work on the project. I don't know what's stopping this site from working with recent versions of Hugo, but it would be good to bring it up to date.

**Comment by davorg** [comment]
Here are the errors I got:

```
$ hugo serve
Start building sites …
hugo v0.93.3+extended linux/amd64 BuildDate=unknown
goroutine 304 [running]:
runtime/debug.Stack()
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/convert.go:187 +0x185
panic({0x55778185d8c0, 0xc00f911860})
        /usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/alecthomas/chroma/lexers/r.popRule.func1(0xc011b31b80)
        /usr/share/gocode/src/github.com/alecthomas/chroma/lexers/r/raku.go:1370 +0x2b7
github.com/alecthomas/chroma.MutatorFunc.Mutate(0x19d?, 0x1c0?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:24 +0x1f
github.com/alecthomas/chroma.Mutators.func1(0x1?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:30 +0x75
github.com/alecthomas/chroma.MutatorFunc.Mutate(0xc01569341c?, 0x19d?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:24 +0x1f
github.com/alecthomas/chroma.(*LexerState).Iterator(0xc011b31b80)
        /usr/share/gocode/src/github.com/alecthomas/chroma/regexp.go:370 +0x392
github.com/alecthomas/chroma.(*coalescer).Tokenise.func1()
        /usr/share/gocode/src/github.com/alecthomas/chroma/coalesce.go:15 +0x2f
github.com/alecthomas/chroma.Iterator.Tokens(0xc0150ce570)
        /usr/share/gocode/src/github.com/alecthomas/chroma/iterator.go:15 +0x4b
github.com/alecthomas/chroma/formatters/html.(*Formatter).Format(0x55778194b788?, {0x55778193d6c8, 0xc0150ce540}, 0x0?, 0x0?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/formatters/html/html.go:181 +0x30
github.com/gohugoio/hugo/markup/highlight.highlight({0x7f53be5b1330?, 0xc010f179e0}, {0xc0058f5ba0, 0x19d}, {0xc0121e6af6?, 0x5?}, {0x0, 0x0, 0x0}, {{0x557780fd7a58, ...}, ...})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/highlight/highlight.go:205 +0x6b3
github.com/gohugoio/hugo/markup/highlight.chromaHighlighter.RenderCodeblock({{{0x557780fd7a58, 0x7}, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, {0x0, 0x0}, ...}}, ...)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/highlight/highlight.go:132 +0x216
github.com/gohugoio/hugo/markup/goldmark/codeblocks.(*htmlRenderer).renderCodeBlock(0xc01355bc20?, {0x55778194f930?, 0xc010f179e0}, {0xc01039a000, 0x4642, 0x4e69}, {0x55778195ac30?, 0xc0135762d0}, 0x69?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/codeblocks/render.go:124 +0x848
github.com/yuin/goldmark/renderer.(*renderer).Render.func2({0x55778195ac30, 0xc0135762d0}, 0x20?)
        /usr/share/gocode/src/github.com/yuin/goldmark/renderer/renderer.go:166 +0xc7
github.com/yuin/goldmark/ast.walkHelper({0x55778195ac30, 0xc0135762d0}, 0xc00578f720)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:503 +0xbe
github.com/yuin/goldmark/ast.walkHelper({0x55778195b650, 0xc01353e120}, 0xc00578f720)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.Walk(...)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:487
github.com/yuin/goldmark/renderer.(*renderer).Render(0xc0004a6410?, {0x55778193d6a8?, 0xc010f179e0?}, {0xc01039a000?, 0x4642?, 0x4e69?}, {0x55778195b650?, 0xc01353e120?})
        /usr/share/gocode/src/github.com/yuin/goldmark/renderer/renderer.go:161 +0x225
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert(0xc00ec026c0, {{0xc01039a000, 0x4642, 0x4e69}, 0x1, 0xc010f174d0})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/convert.go:213 +0x5b2
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContentWithConverter(0xc0011ce540, {0x557781944590?, 0xc00ec026c0?}, {0xc01039a000?, 0x0?, 0x0?}, 0x0?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:572 +0xa3
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContent(0xc0011ce540, {0xc01039a000, 0x4642, 0x4e69}, 0x0?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:568 +0x8a
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:123 +0x30e
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func2({0x55777f7d5d39?, 0x1?})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:198 +0x1b
github.com/gohugoio/hugo/lazy.(*Init).withTimeout.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/lazy/init.go:188 +0x3c
created by github.com/gohugoio/hugo/lazy.(*Init).withTimeout
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/lazy/init.go:187 +0x11e
goroutine 256 [running]:
runtime/debug.Stack()
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/convert.go:187 +0x185
panic({0x55778185d8c0, 0xc018a0c660})
        /usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/alecthomas/chroma/lexers/r.popRule.func1(0xc0117d4210)
        /usr/share/gocode/src/github.com/alecthomas/chroma/lexers/r/raku.go:1370 +0x2b7
github.com/alecthomas/chroma.MutatorFunc.Mutate(0x1bc?, 0x1c0?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:24 +0x1f
github.com/alecthomas/chroma.Mutators.func1(0x1?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:30 +0x75
github.com/alecthomas/chroma.MutatorFunc.Mutate(0xc015c44de4?, 0x1bc?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:24 +0x1f
github.com/alecthomas/chroma.(*LexerState).Iterator(0xc0117d4210)
        /usr/share/gocode/src/github.com/alecthomas/chroma/regexp.go:370 +0x392
github.com/alecthomas/chroma.(*coalescer).Tokenise.func1()
        /usr/share/gocode/src/github.com/alecthomas/chroma/coalesce.go:15 +0x2f
github.com/alecthomas/chroma.Iterator.Tokens(0xc018677338)
        /usr/share/gocode/src/github.com/alecthomas/chroma/iterator.go:15 +0x4b
github.com/alecthomas/chroma/formatters/html.(*Formatter).Format(0x55778194b788?, {0x55778193d6c8, 0xc018677308}, 0x0?, 0x0?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/formatters/html/html.go:181 +0x30
github.com/gohugoio/hugo/markup/highlight.highlight({0x7f53be5b1330?, 0xc005333470}, {0xc018a12380, 0x1bc}, {0xc01606b140?, 0x5?}, {0x0, 0x0, 0x0}, {{0x557780fd7a58, ...}, ...})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/highlight/highlight.go:205 +0x6b3
github.com/gohugoio/hugo/markup/highlight.chromaHighlighter.RenderCodeblock({{{0x557780fd7a58, 0x7}, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, {0x0, 0x0}, ...}}, ...)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/highlight/highlight.go:132 +0x216
github.com/gohugoio/hugo/markup/goldmark/codeblocks.(*htmlRenderer).renderCodeBlock(0xc00580f050?, {0x55778194f930?, 0xc005333470}, {0xc00ba48a80, 0x5d58, 0x67ce}, {0x55778195ac30?, 0xc011ac67e0}, 0xce?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/codeblocks/render.go:124 +0x848
github.com/yuin/goldmark/renderer.(*renderer).Render.func2({0x55778195ac30, 0xc011ac67e0}, 0x20?)
        /usr/share/gocode/src/github.com/yuin/goldmark/renderer/renderer.go:166 +0xc7
github.com/yuin/goldmark/ast.walkHelper({0x55778195ac30, 0xc011ac67e0}, 0xc00578b720)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:503 +0xbe
github.com/yuin/goldmark/ast.walkHelper({0x55778195b650, 0xc0123e0f30}, 0xc00578b720)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.Walk(...)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:487
github.com/yuin/goldmark/renderer.(*renderer).Render(0xc0004a6410?, {0x55778193d6a8?, 0xc005333470?}, {0xc00ba48a80?, 0x5d58?, 0x67ce?}, {0x55778195b650?, 0xc0123e0f30?})
        /usr/share/gocode/src/github.com/yuin/goldmark/renderer/renderer.go:161 +0x225
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert(0xc011347200, {{0xc00ba48a80, 0x5d58, 0x67ce}, 0x1, 0xc005332c90})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/convert.go:213 +0x5b2
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContentWithConverter(0xc0011cf880, {0x557781944590?, 0xc011347200?}, {0xc00ba48a80?, 0x0?, 0x0?}, 0x0?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:572 +0xa3
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContent(0xc0011cf880, {0xc00ba48a80, 0x5d58, 0x67ce}, 0x0?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:568 +0x8a
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:123 +0x30e
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func2({0x0?, 0x0?})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:198 +0x1b
github.com/gohugoio/hugo/lazy.(*Init).withTimeout.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/lazy/init.go:188 +0x3c
created by github.com/gohugoio/hugo/lazy.(*Init).withTimeout
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/lazy/init.go:187 +0x11e
goroutine 257 [running]:
runtime/debug.Stack()
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/convert.go:187 +0x185
panic({0x55778185d8c0, 0xc0155c1518})
        /usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/alecthomas/chroma/lexers/r.popRule.func1(0xc003d3c840)
        /usr/share/gocode/src/github.com/alecthomas/chroma/lexers/r/raku.go:1370 +0x2b7
github.com/alecthomas/chroma.MutatorFunc.Mutate(0x187?, 0x1c0?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:24 +0x1f
github.com/alecthomas/chroma.Mutators.func1(0x1?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:30 +0x75
github.com/alecthomas/chroma.MutatorFunc.Mutate(0xc018bda7c4?, 0x187?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:24 +0x1f
github.com/alecthomas/chroma.(*LexerState).Iterator(0xc003d3c840)
        /usr/share/gocode/src/github.com/alecthomas/chroma/regexp.go:370 +0x392
github.com/alecthomas/chroma.(*coalescer).Tokenise.func1()
        /usr/share/gocode/src/github.com/alecthomas/chroma/coalesce.go:15 +0x2f
github.com/alecthomas/chroma.Iterator.Tokens(0xc0187b9590)
        /usr/share/gocode/src/github.com/alecthomas/chroma/iterator.go:15 +0x4b
github.com/alecthomas/chroma/formatters/html.(*Formatter).Format(0x55778194b788?, {0x55778193d6c8, 0xc0187b9560}, 0x0?, 0x0?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/formatters/html/html.go:181 +0x30
github.com/gohugoio/hugo/markup/highlight.highlight({0x7f53be5b1330?, 0xc00d8af830}, {0xc016d9eb60, 0x187}, {0xc011c6a920?, 0x5?}, {0x0, 0x0, 0x0}, {{0x557780fd7a58, ...}, ...})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/highlight/highlight.go:205 +0x6b3
github.com/gohugoio/hugo/markup/highlight.chromaHighlighter.RenderCodeblock({{{0x557780fd7a58, 0x7}, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, {0x0, 0x0}, ...}}, ...)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/highlight/highlight.go:132 +0x216
github.com/gohugoio/hugo/markup/goldmark/codeblocks.(*htmlRenderer).renderCodeBlock(0xc0156c8360?, {0x55778194f930?, 0xc00d8af830}, {0xc0156da000, 0x7585, 0x8266}, {0x55778195ac30?, 0xc0156e7320}, 0x66?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/codeblocks/render.go:124 +0x848
github.com/yuin/goldmark/renderer.(*renderer).Render.func2({0x55778195ac30, 0xc0156e7320}, 0x20?)
        /usr/share/gocode/src/github.com/yuin/goldmark/renderer/renderer.go:166 +0xc7
github.com/yuin/goldmark/ast.walkHelper({0x55778195ac30, 0xc0156e7320}, 0xc00077f720)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:503 +0xbe
github.com/yuin/goldmark/ast.walkHelper({0x55778195b650, 0xc0077017a0}, 0xc00077f720)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.Walk(...)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:487
github.com/yuin/goldmark/renderer.(*renderer).Render(0xc0004a6410?, {0x55778193d6a8?, 0xc00d8af830?}, {0xc0156da000?, 0x7585?, 0x8266?}, {0x55778195b650?, 0xc0077017a0?})
        /usr/share/gocode/src/github.com/yuin/goldmark/renderer/renderer.go:161 +0x225
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert(0xc011347440, {{0xc0156da000, 0x7585, 0x8266}, 0x1, 0xc00d8aeff0})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/convert.go:213 +0x5b2
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContentWithConverter(0xc0011cfa40, {0x557781944590?, 0xc011347440?}, {0xc0156da000?, 0x0?, 0x0?}, 0x0?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:572 +0xa3
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContent(0xc0011cfa40, {0xc0156da000, 0x7585, 0x8266}, 0xc0?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:568 +0x8a
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:123 +0x30e
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func2({0x0?, 0x0?})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:198 +0x1b
github.com/gohugoio/hugo/lazy.(*Init).withTimeout.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/lazy/init.go:188 +0x3c
created by github.com/gohugoio/hugo/lazy.(*Init).withTimeout
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/lazy/init.go:187 +0x11e
goroutine 234 [running]:
runtime/debug.Stack()
        /usr/lib/golang/src/runtime/debug/stack.go:24 +0x65
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/convert.go:187 +0x185
panic({0x55778185d8c0, 0xc01a984060})
        /usr/lib/golang/src/runtime/panic.go:838 +0x207
github.com/alecthomas/chroma/lexers/r.popRule.func1(0xc0059600b0)
        /usr/share/gocode/src/github.com/alecthomas/chroma/lexers/r/raku.go:1370 +0x2b7
github.com/alecthomas/chroma.MutatorFunc.Mutate(0x1ec?, 0x200?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:24 +0x1f
github.com/alecthomas/chroma.Mutators.func1(0x1?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:30 +0x75
github.com/alecthomas/chroma.MutatorFunc.Mutate(0xc01a9a119c?, 0x1ec?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/mutators.go:24 +0x1f
github.com/alecthomas/chroma.(*LexerState).Iterator(0xc0059600b0)
        /usr/share/gocode/src/github.com/alecthomas/chroma/regexp.go:370 +0x392
github.com/alecthomas/chroma.(*coalescer).Tokenise.func1()
        /usr/share/gocode/src/github.com/alecthomas/chroma/coalesce.go:15 +0x2f
github.com/alecthomas/chroma.Iterator.Tokens(0xc01a6f46a8)
        /usr/share/gocode/src/github.com/alecthomas/chroma/iterator.go:15 +0x4b
github.com/alecthomas/chroma/formatters/html.(*Formatter).Format(0x55778194b788?, {0x55778193d6c8, 0xc01a6f4678}, 0x0?, 0x0?)
        /usr/share/gocode/src/github.com/alecthomas/chroma/formatters/html/html.go:181 +0x30
github.com/gohugoio/hugo/markup/highlight.highlight({0x7f53be5b1330?, 0xc011256f30}, {0xc00f2eec00, 0x1ec}, {0xc01a6fc8e6?, 0x5?}, {0x0, 0x0, 0x0}, {{0x557780fd7a58, ...}, ...})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/highlight/highlight.go:205 +0x6b3
github.com/gohugoio/hugo/markup/highlight.chromaHighlighter.RenderCodeblock({{{0x557780fd7a58, 0x7}, 0x1, 0x1, 0x0, 0x0, 0x1, 0x0, {0x0, 0x0}, ...}}, ...)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/highlight/highlight.go:132 +0x216
github.com/gohugoio/hugo/markup/goldmark/codeblocks.(*htmlRenderer).renderCodeBlock(0xc01723bef0?, {0x55778194f930?, 0xc011256f30}, {0xc01721e000, 0xa39b, 0xb518}, {0x55778195ac30?, 0xc017241440}, 0x18?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/codeblocks/render.go:124 +0x848
github.com/yuin/goldmark/renderer.(*renderer).Render.func2({0x55778195ac30, 0xc017241440}, 0x20?)
        /usr/share/gocode/src/github.com/yuin/goldmark/renderer/renderer.go:166 +0xc7
github.com/yuin/goldmark/ast.walkHelper({0x55778195ac30, 0xc017241440}, 0xc00bc83720)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:503 +0xbe
github.com/yuin/goldmark/ast.walkHelper({0x55778195b650, 0xc016c7f5f0}, 0xc00bc83720)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.Walk(...)
        /usr/share/gocode/src/github.com/yuin/goldmark/ast/ast.go:487
github.com/yuin/goldmark/renderer.(*renderer).Render(0xc0004a6410?, {0x55778193d6a8?, 0xc011256f30?}, {0xc01721e000?, 0xa39b?, 0xb518?}, {0x55778195b650?, 0xc016c7f5f0?})
        /usr/share/gocode/src/github.com/yuin/goldmark/renderer/renderer.go:161 +0x225
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert(0xc00ec02900, {{0xc01721e000, 0xa39b, 0xb518}, 0x1, 0xc011256600})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/markup/goldmark/convert.go:213 +0x5b2
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContentWithConverter(0xc0011cfc00, {0x557781944590?, 0xc00ec02900?}, {0xc01721e000?, 0x0?, 0x0?}, 0x0?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:572 +0xa3
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContent(0xc0011cfc00, {0xc01721e000, 0xa39b, 0xb518}, 0xc0?)
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:568 +0x8a
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:123 +0x30e
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func2({0x55777f7d5d39?, 0x1?})
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/hugolib/page__per_output.go:198 +0x1b
github.com/gohugoio/hugo/lazy.(*Init).withTimeout.func1()
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/lazy/init.go:188 +0x3c
created by github.com/gohugoio/hugo/lazy.(*Init).withTimeout
        /builddir/build/BUILD/hugo-0.93.3/_build/src/github.com/gohugoio/hugo/lazy/init.go:187 +0x11e
Error: Error building site: "/home/dave/git/theweeklychallenge/content/blog/p6-review-challenge-033.md:1:1": [BUG] goldmark: runtime error: index out of range [-1]: create an issue on GitHub attaching the file in: /tmp/hugo_bugs/goldmark_6076e277f1533c9fbc832e73fc0930be.txt
Built in 3241 ms
```

**Comment by manwar** [comment]
@davorg I would appreciate if you could please help us to make it work with the latest Hugo.
